/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author gateway
 */
public class Panel1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public Panel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtRebotesTotales = new javax.swing.JTextField();
        txtBloqueosTotales = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPuntosTotales = new javax.swing.JTextField();
        txtAsistenciasTotales = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRobosTotales = new javax.swing.JTextField();
        txtPartidosJugados = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMVPsTotales = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRobosTotales1 = new javax.swing.JTextField();
        txtPartidosJugados1 = new javax.swing.JTextField();
        txtRebotesTotales1 = new javax.swing.JTextField();
        txtMVPsTotales1 = new javax.swing.JTextField();
        txtBloqueosTotales1 = new javax.swing.JTextField();
        txtPuntosTotales1 = new javax.swing.JTextField();
        txtAsistenciasTotales1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAtras = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Rebotes Totales:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        add(txtRebotesTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        add(txtBloqueosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel12.setText("Bloqueos Totales:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setText("Puntos Totales:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        add(txtPuntosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));
        add(txtAsistenciasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel13.setText("Asistencias Totales:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel15.setText("Robos Totales:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        add(txtRobosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        txtPartidosJugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartidosJugadosActionPerformed(evt);
            }
        });
        add(txtPartidosJugados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel16.setText("Partidos Jugados");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        add(txtMVPsTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel17.setText("MVP's Totales:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        add(txtRobosTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 179, -1, -1));

        txtPartidosJugados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartidosJugados1ActionPerformed(evt);
            }
        });
        add(txtPartidosJugados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 219, -1, -1));
        add(txtRebotesTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 19, -1, -1));
        add(txtMVPsTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 259, -1, -1));
        add(txtBloqueosTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 59, -1, -1));
        add(txtPuntosTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 99, -1, -1));
        add(txtAsistenciasTotales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 139, -1, -1));

        jLabel1.setText("Resultado:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 332, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 299, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 391, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPartidosJugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartidosJugadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartidosJugadosActionPerformed

    private void txtPartidosJugados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartidosJugados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartidosJugados1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtAsistenciasTotales;
    private javax.swing.JTextField txtAsistenciasTotales1;
    private javax.swing.JTextField txtBloqueosTotales;
    private javax.swing.JTextField txtBloqueosTotales1;
    private javax.swing.JTextField txtMVPsTotales;
    private javax.swing.JTextField txtMVPsTotales1;
    private javax.swing.JTextField txtPartidosJugados;
    private javax.swing.JTextField txtPartidosJugados1;
    private javax.swing.JTextField txtPuntosTotales;
    private javax.swing.JTextField txtPuntosTotales1;
    private javax.swing.JTextField txtRebotesTotales;
    private javax.swing.JTextField txtRebotesTotales1;
    private javax.swing.JTextField txtRobosTotales;
    private javax.swing.JTextField txtRobosTotales1;
    // End of variables declaration//GEN-END:variables
}
